const PROJECTS = [
  {
    id: 'campus-marketplace',
    title: 'SLSU Campus Market Place',
    category: 'web',
    categoryLabel: 'Web App',
    tags: ['Firebase', 'Cloudinary', 'Marketplace'],
    year: '2024',
    desc: 'Campus marketplace for SLSU students to buy and sell preloved items — listings, search, seller tools, buyer–seller chat, notifications, and receipts, with Firebase auth/Firestore and Cloudinary uploads.',
    img: 'assets/campus-marketplace.png',
    url: 'https://slsu-marketplace.org/',
  },
  {
    id: 'aspirewrite',
    title: 'AspireWrite',
    category: 'web',
    categoryLabel: 'Web App',
    tags: ['Firebase', 'Cloudinary', 'Content Platform'],
    year: '2023',
    desc: 'Full-stack literary platform for discovering, uploading, and reading creative works — auth, category browsing, search, comments, ratings, and author profiles using Firebase and Cloudinary.',
    img: 'assets/aspirewrite.png',
    url: 'https://aspirewrite.org/',
  },
  {
    id: 'fitnesshood',
    title: 'FitnessHood',
    category: 'system',
    categoryLabel: 'Web System',
    tags: ['Next.js', 'Prisma', 'Supabase'],
    year: '2025',
    desc: 'Full-stack gym attendance and membership system with admin/member portals — QR check-in, registration, payments, loyalty features, and Excel/PDF reporting on Next.js, Prisma, and Supabase.',
    img: 'assets/fitnesshood.png',
    url: 'https://www.fitnesshood.org/',
  },
  {
    id: 'studio8teen',
    title: 'Studio 8teen Photography',
    category: 'system',
    categoryLabel: 'Web System',
    tags: ['React', 'Supabase', 'Booking'],
    year: '2026',
    desc: 'Photography studio booking platform (StudioBook) with scheduling, payments, client galleries, mood boards, FAQ chatbot, and QR booking checks — React, Supabase, and Cloudinary.',
    img: 'assets/studio8teen.png',
    url: 'https://www.studio8teen.org/',
  },
  {
    id: 'code-clash',
    title: 'Code Clash',
    category: 'android',
    categoryLabel: 'Android',
    tags: ['Android', 'Firebase', 'Java'],
    year: '2025',
    desc: 'Gamified Android app for Java fundamentals — interactive lessons, quizzes, coding challenges, real-time code execution, and an instructor dashboard with Firebase Auth and Cloud Firestore.',
    img: 'assets/code-clash.png',
    url: null,
  },
];

const PROJECT_FILTERS = [
  { value: 'all', label: 'All' },
  { value: 'web', label: 'Web App' },
  { value: 'system', label: 'Web System' },
  { value: 'android', label: 'Android' },
];
