const PROJECTS = [
  {
    id: 'campus-marketplace',
    title: 'SLSU Campus Market Place',
    category: 'web',
    categoryLabel: 'Web App',
    tags: ['Firebase', 'Cloudinary', 'Marketplace'],
    year: '2025',
    blurb: 'Campus buy-and-sell for SLSU students — listings, in-app chat, and receipts without leaving school.',
    desc: 'Student marketplace for preloved books, gadgets, and uniforms: search, seller tools, buyer–seller chat, notifications, and receipts on Firebase Auth/Firestore with Cloudinary uploads.',
    img: 'assets/campus-marketplace.png',
    url: 'https://slsu-marketplace.org/',
  },
  {
    id: 'aspirewrite',
    title: 'AspireWrite',
    category: 'web',
    categoryLabel: 'Web App',
    tags: ['Firebase', 'Cloudinary', 'Content'],
    year: '2025',
    blurb: 'A literary home for writers and readers — publish work, browse by category, and leave ratings.',
    desc: 'Literary platform for discovering, uploading, and reading creative works, with auth, category browse, search, comments, ratings, and author profiles on Firebase and Cloudinary.',
    img: 'assets/aspirewrite.png',
    url: 'https://aspirewrite.org/',
  },
  {
    id: 'fitnesshood',
    title: 'FitnessHood',
    category: 'system',
    categoryLabel: 'Web System',
    tags: ['Next.js', 'Prisma', 'Supabase'],
    year: '2025',
    blurb: 'Gym ops in one place — QR check-in, memberships, payments, and admin reports.',
    desc: 'Gym attendance and membership system with admin and member portals: QR check-in, registration, payments, loyalty, and Excel/PDF reports on Next.js, Prisma, and Supabase.',
    img: 'assets/fitnesshood.png',
    url: 'https://www.fitnesshood.org/',
  },
  {
    id: 'slsu-asset',
    title: 'SLSU Asset Management',
    category: 'system',
    categoryLabel: 'Web System',
    tags: ['React', 'Expo', 'DINOv2'],
    year: '2026',
    blurb: 'Staff scan campus property with the camera — DINOv2 matching, admin portal, and inventory reports.',
    desc: 'SLSU Lucena asset inventory with role-based auth, React admin, Expo camera scan, DINOv2 few-shot matching, scan history, and PDF/Excel reports on Supabase and Cloudinary.',
    img: 'assets/slsu-asset-management.png',
    url: 'https://www.slsu-asset-management.com/login',
    apk: 'https://expo.dev/accounts/abbycoleen/projects/slsu-asset-inventory/builds/fca7c1e2-57b2-428d-9144-d8eb4d63be6b',
  },
  {
    id: 'studio8teen',
    title: 'Studio 8teen Photography',
    category: 'system',
    categoryLabel: 'Web System',
    tags: ['React', 'Supabase', 'Booking'],
    year: '2026',
    blurb: 'Photography bookings end to end — schedule, pay, galleries, and QR check-in at the studio.',
    desc: 'StudioBook for Studio 8teen: scheduling, payment verification, client galleries, mood boards, pose suggestions, FAQ chatbot, and QR booking checks on React, Supabase, and Cloudinary.',
    img: 'assets/studio8teen.png',
    url: 'https://www.studio8teen.org/',
  },
  {
    id: 'code-clash',
    title: 'Code Clash',
    category: 'android',
    categoryLabel: 'Android',
    tags: ['Android', 'Firebase', 'Java'],
    year: '2025',
    blurb: 'Learn Java on Android — lessons, quizzes, and live coding challenges with an instructor view.',
    desc: 'Gamified Java learning app: interactive lessons, quizzes, coding challenges, real-time code execution, and an instructor dashboard on Firebase Auth and Cloud Firestore.',
    img: 'assets/code-clash.png',
    url: 'https://github.com/Tannntannn/CodeClash',
    apk: 'https://drive.google.com/drive/folders/1mIXLeHJuPhR1FRi6jEWHCAPd5wf3GUDo?usp=sharing',
  },
];

const PROJECT_FILTERS = [
  { value: 'all', label: 'All' },
  { value: 'web', label: 'Web App' },
  { value: 'system', label: 'Web System' },
  { value: 'android', label: 'Android' },
];
